name = "audit-docs"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./site",entry-point = "workers-site"}
compatibility_date = "2021-12-08"
